#-------------------------------
# General Site Settings
baseurl: "" 
url: "https://SeongjinL.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Site Settings

title: Avenco
logo: '/images/logo.png'
description: SeongLee - Creative Portfolio

menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Pages'
      submenu:
      - url: '/about'
        title: 'About'
      - url: /elements
        title: Elements

# Call to action button
cta__button__text: Get in touch

# Add global cover image
cover__image: '/images/37.jpg'

#-------------------------------
# Author Settings

author:
  name: SeongJin Lee
  title: 안녕하세요. 저는 엔지니어 길을 걷고있는 이성진이라고 합니다.
  bio: 제가 만들어 놓은 이력서를 함께 보시고 제가 진행하고 있는 클라우드엔지니어, 서버엔지니어, 데이터엔지니어에 관련있는 프로젝트를 진행하였고 그것을 재미있게 봐주시 바랍니다.
  image: '/images/01.jpg'
  avatar: '/images/avatar.jpg'
  button__text: See my Projects

#-------------------------------
# Project Settings

project__settings:
  projects__title: Latest <span class="text-span">Works</span> # 추가한 이유는  'text-span' 클래슨느 하이라이트 텍스트입니다.
  projects__description: asdasdasd


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 6
paginate_path: "/blog/page/:num"


# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed
