#-------------------------------
# General Site Settings
baseurl: "" 
url: "https://SeongjinL.github.io" # the base hostname & protocol for your site, e.g. http://example.com




#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 6
paginate_path: "/blog/page/:num"


# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "개인공부"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "프로젝트"


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed

# Analytics
analytics: 
  provider: "google-gtag"
  google:
    tracking_id :"G-4M15W974C6"
    anonymize_ip : false