#-------------------------------
# Site Settings

title: SeongLee Code
logo: # You can add own logo. For example '/images/logo.png'.
description: SeongLee – Portfolio Project-Code

menu__settings:
  menu__items:
    - title: '메인'
      url: '/'
    - title: '프로젝트'
      url: '/projects/'
    - title: '개인공부'
      url: '/blog/'
    - title: '이력서 및 자소서'
      submenu:
      - url: '/about'
        title: '이력서'
      - url: '/elements'
        title: '자기소개서'

# Call to action button
cta__button__text: Get in touch

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/images/37.jpg'


#-------------------------------
# Author Settings

author:
  name: Seongjin Lee
  title: Hello I’m Seongjin Lee
  bio: 안녕하신가여
  image: '/images/01.jpg'
  avatar: '/images/avatar.jpg'
  button__text: See my works


#-------------------------------
# Projects Settings

projects__settings:
  projects__title: Latest <span class="text-span">Project</span> # Add a 'text-span' class to highlight text.
  projects__description: 제가 만든 프로젝트를 구경하고 싶으시다면 VIEW ALL을 눌러주세요 !


#-------------------------------
# Blog Section

blog__settings:
  blog__title: Study <span class="text-span">Alone</span> Posts # Add a 'text-span' class to highlight text.
  blog__description:


#-------------------------------
# Testimonials Section

testimonial__title: Someone's <span class="text-span">Material</span> # Add a 'text-span' class to highlight text.

#-------------------------------
# Contact Settings

contact__settings:
  contact__email: your@email.com # Add your email for contact form
  contact__title: <span class="text-span">Get</span> in touch # Add a title to your form
  contact__description: Avenco comes with a built-in contact form. # Add a description to your form

# NOTE
# Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: <span class="text-span">Join</span> my mailing list # Add your title
  mailchimp__text: " 'Get inspiration, updates and', 'cool stuff about design!' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: "G-4M15W974C6"# Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-github", link: "https://github.com"}
- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {icon: "ion-logo-codepen", link: "https://codepen.io"}
- {icon: "ion-logo-vimeo", link: "https://vimeo.com"}
- {icon: "ion-logo-youtube", link: "https://youtube.com"}